Fix enum sequence and struct sequence validation
sony/nmos-cpp pull request #412
Opened 2024-10-11 14:12 UTC by jonathan-r-thorpe

- Enum sequences and struct sequences are failing the constraint validation even though they were valid.
- This is because the enum and struct sequences were not being treated like arrays.  
- This PR fixes the problem. 
- It also includes improved logging/error reporting.
- The draft MS-05-02 test suite in NMOS Testing has been updated to trap this bug.

2024-10-11 21:03 UTC, lo-simon requested changes
Suggest minor changes. Rest LGTM.

2024-10-11 21:30 UTC, garethsb commented on Development/nmos/control_protocol_methods.cpp
> +        slog::log<slog::severities::error>(gate, SLOG_FLF) << utility::conversions::to_utf8string(ss.str());
Why write into a separate stringstream first at all?

2024-10-11 21:34 UTC, garethsb commented on Development/nmos/control_protocol_methods.cpp
> +                slog::log<slog::severities::error>(gate, SLOG_FLF) << utility::conversions::to_utf8string(ss.str());
Why is the `ss.str()` not used in the following `return details::make_nc_method_result(...)` ?

2024-10-14 07:22 UTC, jonathan-r-thorpe commented on Development/nmos/control_protocol_methods.cpp
> +                slog::log<slog::severities::error>(gate, SLOG_FLF) << utility::conversions::to_utf8string(ss.str());
Good spot - it should be:
`return details::make_nc_method_result_error({ nc_method_status::parameter_error}, ss.str())`

2024-10-14 15:17 UTC, merged